kind: pipeline
type: docker
name: default

steps:
  - name: build & test
    image: gcc:latest
    commands:
      - apt update && apt install -y valgrind
      - make clean
      - make build
      - make memcheck